version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      lan-pub:
        ipv4_address: 192.168.0.201
      traefik-proxy: {}
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"  # можно удалить после проверки
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic
      - ./letsencrypt:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/var/log/traefik
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --api.debug=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.le.acme.email=yuriukovalev22@icloud.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web

      - --log.level=DEBUG
      - --accesslog=true

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host(`proxy.dit-system.ru`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls=true
      - traefik.http.routers.traefik-dashboard.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard.service=api@internal
      

networks:
  lan-pub:
    external: true
  traefik-proxy:
    external: true